baseURL = "https://example.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "Example - CV"

[params]
pages = 1
colorDark = "#333"
colorLight = "#eee"
colorPageBackground = "#ccc"
colorPrimary = "#a34b4b"
colorPrimaryText = "#ddd"
colorRightColumnBackground = "#e3e3e3"
colorSecondary = "#444"

[params.themes.light]
colorDark = "#333"
colorLight = "#eee"
colorPageBackground = "#ccc"
colorPrimary = "#a34b4b"
colorPrimaryText = "#ddd"
colorRightColumnBackground = "#e3e3e3"
colorSecondary = "#444"

[params.themes.dark]
colorDark = "#eee"
colorLight = "#333"
colorPageBackground = "#2e2e30"
colorPrimary = "#a34b4b"
colorPrimaryText = "#ddd"
colorRightColumnBackground = "#3e3e41"
colorSecondary = "#444"

[params.fonts]
fontSans = "Open Sans"
fontMono = "Cascadia Mono"
fontHeading = "Oswald"
# lineSize = "14pt"
